/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const risks_Logic = require('./code/risks-logic');

class riskmanagement_I811991Service extends LCAPApplicationService {
    async init() {

        this.after('READ', 'Risks', async (results, request) => {
            await risks_Logic({
                results,
                request
            });
        });

        return super.init();
    }
}


module.exports = {
    riskmanagement_I811991Service
};